language: python
sudo: false
python:
- '3.4'

addons:
  postgresql: "9.4"

before_script:
- psql -c "CREATE DATABASE wye" -U postgres

install:
- pip install --upgrade pip
- pip install python-coveralls
- pip install -r requirements/dev.txt

script:
- flake8
- py.test --cov --fail-on-template-vars

after_script:
- coveralls
